name: Start Server

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            /home/ubuntu/.nvm/versions/node/v24.17.0/bin/pm2 restart strangers-play-backend
